// Generated by CoffeeScript 1.3.3
(function() {
  var AnnexHandler, discount, fs, glob, path, regex;

  fs = require("fs");

  path = require("path");

  glob = require("glob");

  discount = require("discount");

  regex = {
    markdownFile: /(.*)\.md$/
  };

  AnnexHandler = (function() {

    function AnnexHandler(annex) {
      this.annex = annex;
    }

    AnnexHandler.prototype.init = function(files, cb) {
      this.files = files;
      return cb();
    };

    AnnexHandler.prototype.processFile = function(file, cb) {
      var matches, outName, self;
      self = this;
      if (matches = regex.markdownFile.exec(file)) {
        outName = "" + matches[1] + ".html";
        fs.readFile(path.join(this.annex.root, file), "utf8", function(err, contents) {
          return self.annex.writeFile(outName, discount.parse(contents), cb);
        });
        return;
      }
      return cb();
    };

    return AnnexHandler;

  })();

  module.exports = function(annex) {
    return new AnnexHandler(annex);
  };

}).call(this);
