// Generated by CoffeeScript 1.3.3
(function() {
  var AnnexHandler, discount, glob;

  glob = require("glob");

  discount = require("discount");

  AnnexHandler = (function() {

    function AnnexHandler(cork, config) {
      this.cork = cork;
      this.config = config;
    }

    AnnexHandler.prototype.init = function(files, cb) {
      this.files = files;
      return cb();
    };

    AnnexHandler.prototype.listPages = function(cb) {};

    return AnnexHandler;

  })();

  module.exports = function(cork, annexRoot) {
    return new AnnexHandler(cork, annexRoot);
  };

}).call(this);
